#https://github.com/revolunet/create-react-app-circleci/blob/master/.circleci/config.yml
defaults: &defaults
  working_directory: ~/zeroview
  docker:
    - image: circleci/node:lts
    # - image: docker:stable-git
    - image: selenium/standalone-chrome:3.1.0

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - run: yarn test

  build:
    <<: *defaults
    steps:
      - checkout
      - run: yarn build

  build-example:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn build-example





workflows:
  version: 2
  deploy_docs:
    jobs:
      - prepare
      - test
      - build:
          requires:
          - prepare
          filters:
            branches:
              only: master
      - build-example:
          requires:
          - prepare
          filters:
            branches:
              only: master
