#https://github.com/revolunet/create-react-app-circleci/blob/master/.circleci/config.yml
defaults: &defaults
  working_directory: ~/zeroview
  docker:
    - image: circleci/node:8
    # - image: selenium/standalone-chrome:3.1.0

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - deploy_ghpages.sh
  build-example:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn build-example
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - deploy_ghpages.sh
  deploy-example:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - working-
      - persist_to_workspace:
          root: .
          paths:
            - null
      - run: chmod +x ./deploy_ghpages.sh
      - run: ./deploy_ghpages.sh




workflows:
  version: 2
  deploy_docs:
    jobs:
      - prepare
      - build-example:
          requires:
          - prepare
      - deploy-example:
          requires:
          - build-example
