#https://github.com/revolunet/create-react-app-circleci/blob/master/.circleci/config.yml
defaults: &defaults
  working_directory: ~/zeroview
  docker:
    - image: circleci/node:8
    - image: docker:stable-git
    # - image: selenium/standalone-chrome:3.1.0

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - deploy_gh_pages.sh
  build-example:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn build-example
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - deploy_gh_pages.sh
  deploy-example:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
          - "10:58:28:b5:0f:2a:1b:c5:da:df:a8:c0:14:fc:15:6b"
      - run: chmod +x ./deploy_gh_pages.sh
      # - run: sh ./deploy_gh_pages.sh ./dist
      - deploy:
          name: Deploy website
          command: |
            git config --global user.name "Circle CI"
            git config --global user.email "bot@circleci.com"
            sh ./deploy_gh_pages.sh ./dist




workflows:
  version: 2
  deploy_docs:
    jobs:
      - prepare
      - build-example:
          requires:
          - prepare
      - deploy-example:
          requires:
          - build-example
